FROM python:3.11-slim

WORKDIR /app
RUN apt-get update && apt-get install -y \
    libgl1 libglib2.0-0 libsm6 libxext6 libxrender1 \
    curl && \
    rm -rf /var/lib/apt/lists/*
RUN python -m pip install --upgrade pip

COPY code/ocr/requirements-stub.txt /app/ocr-requirements.txt
RUN python -m pip install --no-cache-dir -r /app/ocr-requirements.txt
COPY code/ocr /app

EXPOSE 5000

ENV PYTHONUNBUFFERED=1 \
    FLASK_ENV=production

CMD ["python", "server.py"]
